spring.application.name=LaundryApplication
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
server.port=8080

spring.datasource.username=root
spring.datasource.password=rxYVUNSjQodyMTFjXfEYAUDocRDMvgDD
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://root:rxYVUNSjQodyMTFjXfEYAUDocRDMvgDD@tramway.proxy.rlwy.net:19026/railway

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=laundryxclean69@gmail.com
spring.mail.password=hdbc rgon jbmo gnxx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true